workdir: /root/test1/experiment-0
source_wells:
- A1
- A2
- A3
destination_wells:
- B1
- B2
- B3
volume: 50
wellplate:
    name: corning_96_wellplate_360ul_flat
    location: '1'
tiprack:
    name: opentrons_96_tiprack_20ul
    location: '8'
pipette:
    name: p20_single_gen2
    mount: right
