workdir: /home/locobot/test-ot2/experiment-0
source_wells:
- A1
- A2
- A3
destination_wells:
- B1
- B2
- B3
volume: 50
wellplate:
    name: corning_96_wellplate_360ul_flat
    location: '8'
tiprack:
    name: opentrons_96_tiprack_300ul
    location: '1'
pipette:
    name: p300_single
    mount: left
