wellplate: # Labware object
    name: corning_96_wellplate_360ul_flat
    location: '1'
tiprack:
    name: opentrons_96_tiprack_20ul # Labware Object
    location: '8'
pipette:
    name: p20_single_gen2 # Instrument Object
    mount: right
source_wells: # Optional, user specified
- A1
- A2
- A3
destination_wells: # Optional, user specified
- B1
- B2
- B3
volume: 100 # Optional, user specified
