robots:
  - connection:
      remote_dir: /root/test1
      host: root@192.168.0.104
      port: 22
      key_filename: /Users/abrace/.ssh/ot2_ssh_key
    wellplate:
      name: corning_96_wellplate_360ul_flat
      location: '2'
    tiprack:
      name: opentrons_96_tiprack_20ul
      location: '8'
    pipette:
      name: p20_single_gen2
      mount: right
    sourceplate:
      name: corning_6_wellplate_16.8ml_flat
      location: '3'

  - connection:
      remote_dir: /root/test1
      host: root@192.168.0.103
      port: 22
      key_filename: /Users/abrace/.ssh/ot2_ssh_key
    wellplate:
      name: corning_96_wellplate_360ul_flat
      location: '6'
    tiprack:
      name: opentrons_96_tiprack_20ul
      location: '8'
    pipette:
      name: p20_single_gen2
      mount: right
    sourceplate:
      name: corning_6_wellplate_16.8ml_flat
      location: '3'

output_dir: search_results
