source_wells:
- A1
- A2
- A3
source_volumes:
- 10
- 5
- 10
target_tip: "A1"
target_well: "B1"

wellplate:
    name: corning_96_wellplate_360ul_flat
    location: '1'
sourceplate:
    name: corning_6_wellplate_16.8ml_flat
    location: '3'
tiprack:
    name:  opentrons_96_tiprack_20ul # opentrons_96_tiprack_1000ul 
    location: '8'
pipette:
    name: p20_single_gen2 #p1000_single_gen2 # 
    mount: right
