source_wells:
- A1
- A2

source_volumes:
- 5
- 10


wellplate:
    name: corning_96_wellplate_360ul_flat
    location: '1'
tiprack:
    name: opentrons_96_tiprack_20ul #opentrons_96_tiprack_1000ul
    location: '8'
pipette:
    name: p20_single_gen2 #p1000_single_gen2
    mount: right