source_wells:
- A1
- A2
- A3
destination_wells:
- B1
- B2
- B3
volume: 100
wellplate:
    name: corning_96_wellplate_360ul_flat
    location: '1'
tiprack:
    name: opentrons_96_tiprack_1000ul
    location: '8'
pipette:
    name: p300_single
    mount: left
