# This will error out because volume to be drawn is too large for installed hardware
equipment:
  - name: corning_96_wellplate_360ul_flat
    location: "1"
  - name: opentrons_96_tiprack_20ul #opentrons_96_tiprack_1000ul
    location: "8"
  - name: opentrons_96_tiprack_1000ul
    location: "9"
  - name: p20_single_gen2 #p1000_single_gen2
    mount: right
  - name: p1000_single_gen2
    mount: left
commands:
  - name: example command
    source: A1
    destination: B1
    volume: 1001

metadata:
  protocolName: Example Name
  author: Kyle khippe@anl.gov
  description: some detailed description
  apiLevel: "2.12"
