# This will error out because no pippete exist
equipment:
  - name: p20_single_gen2 #p1000_single_gen2
    mount: right
  - name: p1000_single_gen2
    mount: left

commands:
  - name: example command
    source: A1
    destination: B1
    volume: 100

metadata:
  protocolName: Example Name
  author: Kyle khippe@anl.gov
  description: some detailed description
  apiLevel: "2.12"
